"""Add admin column

Revision ID: 894fe09b2655
Revises: 37fe9d4346cc
Create Date: 2018-04-29 23:53:21.797064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894fe09b2655'
down_revision = '37fe9d4346cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
